// All 50 US states with FIPS-based Data Commons DCIDs
export const US_STATES = [
  { name: 'Alabama', dcid: 'geoId/01', abbr: 'AL', fips: '01' },
  { name: 'Alaska', dcid: 'geoId/02', abbr: 'AK', fips: '02' },
  { name: 'Arizona', dcid: 'geoId/04', abbr: 'AZ', fips: '04' },
  { name: 'Arkansas', dcid: 'geoId/05', abbr: 'AR', fips: '05' },
  { name: 'California', dcid: 'geoId/06', abbr: 'CA', fips: '06' },
  { name: 'Colorado', dcid: 'geoId/08', abbr: 'CO', fips: '08' },
  { name: 'Connecticut', dcid: 'geoId/09', abbr: 'CT', fips: '09' },
  { name: 'Delaware', dcid: 'geoId/10', abbr: 'DE', fips: '10' },
  { name: 'Florida', dcid: 'geoId/12', abbr: 'FL', fips: '12' },
  { name: 'Georgia', dcid: 'geoId/13', abbr: 'GA', fips: '13' },
  { name: 'Hawaii', dcid: 'geoId/15', abbr: 'HI', fips: '15' },
  { name: 'Idaho', dcid: 'geoId/16', abbr: 'ID', fips: '16' },
  { name: 'Illinois', dcid: 'geoId/17', abbr: 'IL', fips: '17' },
  { name: 'Indiana', dcid: 'geoId/18', abbr: 'IN', fips: '18' },
  { name: 'Iowa', dcid: 'geoId/19', abbr: 'IA', fips: '19' },
  { name: 'Kansas', dcid: 'geoId/20', abbr: 'KS', fips: '20' },
  { name: 'Kentucky', dcid: 'geoId/21', abbr: 'KY', fips: '21' },
  { name: 'Louisiana', dcid: 'geoId/22', abbr: 'LA', fips: '22' },
  { name: 'Maine', dcid: 'geoId/23', abbr: 'ME', fips: '23' },
  { name: 'Maryland', dcid: 'geoId/24', abbr: 'MD', fips: '24' },
  { name: 'Massachusetts', dcid: 'geoId/25', abbr: 'MA', fips: '25' },
  { name: 'Michigan', dcid: 'geoId/26', abbr: 'MI', fips: '26' },
  { name: 'Minnesota', dcid: 'geoId/27', abbr: 'MN', fips: '27' },
  { name: 'Mississippi', dcid: 'geoId/28', abbr: 'MS', fips: '28' },
  { name: 'Missouri', dcid: 'geoId/29', abbr: 'MO', fips: '29' },
  { name: 'Montana', dcid: 'geoId/30', abbr: 'MT', fips: '30' },
  { name: 'Nebraska', dcid: 'geoId/31', abbr: 'NE', fips: '31' },
  { name: 'Nevada', dcid: 'geoId/32', abbr: 'NV', fips: '32' },
  { name: 'New Hampshire', dcid: 'geoId/33', abbr: 'NH', fips: '33' },
  { name: 'New Jersey', dcid: 'geoId/34', abbr: 'NJ', fips: '34' },
  { name: 'New Mexico', dcid: 'geoId/35', abbr: 'NM', fips: '35' },
  { name: 'New York', dcid: 'geoId/36', abbr: 'NY', fips: '36' },
  { name: 'North Carolina', dcid: 'geoId/37', abbr: 'NC', fips: '37' },
  { name: 'North Dakota', dcid: 'geoId/38', abbr: 'ND', fips: '38' },
  { name: 'Ohio', dcid: 'geoId/39', abbr: 'OH', fips: '39' },
  { name: 'Oklahoma', dcid: 'geoId/40', abbr: 'OK', fips: '40' },
  { name: 'Oregon', dcid: 'geoId/41', abbr: 'OR', fips: '41' },
  { name: 'Pennsylvania', dcid: 'geoId/42', abbr: 'PA', fips: '42' },
  { name: 'Rhode Island', dcid: 'geoId/44', abbr: 'RI', fips: '44' },
  { name: 'South Carolina', dcid: 'geoId/45', abbr: 'SC', fips: '45' },
  { name: 'South Dakota', dcid: 'geoId/46', abbr: 'SD', fips: '46' },
  { name: 'Tennessee', dcid: 'geoId/47', abbr: 'TN', fips: '47' },
  { name: 'Texas', dcid: 'geoId/48', abbr: 'TX', fips: '48' },
  { name: 'Utah', dcid: 'geoId/49', abbr: 'UT', fips: '49' },
  { name: 'Vermont', dcid: 'geoId/50', abbr: 'VT', fips: '50' },
  { name: 'Virginia', dcid: 'geoId/51', abbr: 'VA', fips: '51' },
  { name: 'Washington', dcid: 'geoId/53', abbr: 'WA', fips: '53' },
  { name: 'West Virginia', dcid: 'geoId/54', abbr: 'WV', fips: '54' },
  { name: 'Wisconsin', dcid: 'geoId/55', abbr: 'WI', fips: '55' },
  { name: 'Wyoming', dcid: 'geoId/56', abbr: 'WY', fips: '56' },
];

export const STATE_BY_DCID = Object.fromEntries(US_STATES.map(s => [s.dcid, s]));
export const STATE_BY_FIPS = Object.fromEntries(US_STATES.map(s => [s.fips, s]));
export const ALL_STATE_DCIDS = US_STATES.map(s => s.dcid);
